# Generated by Django 3.2 on 2024-03-18 06:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('administrator_id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('administrator_name', models.CharField(default='anonymity', max_length=255, null=True)),
                ('administrator_introduction', models.CharField(max_length=255, null=True)),
                ('administrator_pfp', models.ImageField(upload_to='')),
                ('administrator_register', models.DateField(null=True)),
                ('administrator_sex', models.BooleanField(null=True)),
                ('administrator_age', models.IntegerField(null=True)),
                ('administrator_birthday', models.DateField(null=True)),
                ('administrator_phone', models.CharField(max_length=255, null=True)),
                ('administrator_mail', models.CharField(max_length=255, null=True)),
                ('administrator_ip', models.CharField(max_length=255, null=True)),
                ('administrator_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('article_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('article_updated', models.DateTimeField(auto_now=True)),
                ('article_title', models.CharField(max_length=255)),
                ('article_content', models.TextField()),
                ('article_image', models.ImageField(upload_to='')),
                ('article_views', models.PositiveIntegerField(default=0)),
                ('article_commentcnt', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, null=True)),
                ('category_description', models.TextField()),
                ('category_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='anonymity', max_length=255, null=True)),
                ('user_introduction', models.CharField(max_length=255, null=True)),
                ('user_pfp', models.ImageField(upload_to='')),
                ('user_register', models.DateField(null=True)),
                ('user_sex', models.BooleanField(null=True)),
                ('user_age', models.IntegerField(null=True)),
                ('user_birthday', models.DateField(null=True)),
                ('user_phone', models.CharField(max_length=255, null=True)),
                ('user_mail', models.CharField(max_length=255, null=True)),
                ('user_ip', models.CharField(max_length=255, null=True)),
                ('user_state', models.BooleanField(null=True)),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('comment_created', models.DateTimeField(auto_now_add=True)),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app01.article')),
                ('comment_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='app01.user')),
            ],
            options={
                'ordering': ('comment_created',),
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('article_id', 'category_id')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='app01.user'),
        ),
    ]
